server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # User Service 路由 - 注册
        - id: user-register
          uri: lb://USER-SERVICE  # 使用负载均衡和服务名
          predicates:
            - Path=/api/users/register
            - Method=POST

        # User Service 路由 - 登录
        - id: user-login
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/login
            - Method=POST

        # User Service 路由 - 其他
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        # Account Service 路由
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**

        # Transaction Service 路由
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transactions/**

      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

jwt:
  secret: mySecretKeyForFintech2025DevelopmentOnly12345678901234567890
  expiration: 86400000

# 添加 Eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG