server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # User Service 路由 - 注册
        - id: user-register
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/register
            - Method=POST

        # User Service 路由 - 登录
        - id: user-login
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/login
            - Method=POST

        # User Service 路由 - 其他
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        # Account Service 路由
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/accounts/**

        # Transaction Service 路由
        - id: transaction-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/transactions/**

      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG