server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: marcoreus
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.example.fintech.accountservice: INFO