server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 用户注册和登录（不需要认证）
        - id: user-public
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/register,/api/users/login
            - Method=POST

        # 用户其他接口（暂时不使用认证）
        - id: user-protected
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        # 账户服务（暂时不使用认证）
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**

        # 交易服务（暂时不使用认证）
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transactions/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG