server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-public
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/register,/api/users/login
            - Method=POST

        - id: user-protected
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - name: JwtAuthentication

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**
          filters:
            - name: JwtAuthentication

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transactions/**
          filters:
            - name: JwtAuthentication

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG