spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

jwt:
  secret: mySecretKeyForFintech2025DevelopmentOnly12345678901234567890
  expiration: 86400000

logging:
  level:
    org.springframework.cloud: INFO