server:
  port: 8083

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: marcoreus
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.example.fintech.transactionservice: INFO